[workspace]
members = ["json-rpc/client", "json-rpc/server", "paytube"]

resolver = "2"

[workspace.package]
version = "2.3.2"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
agave-feature-set = { path = "../../feature-set" }
agave-reserved-account-keys = { path = "../../reserved-account-keys" }
base64 = "0.22.1"
bincode = "1.3.3"
borsh = { version = "1.5.2", features = ["derive"] }
bs58 = { version = "0.5.1", default-features = false }
clap = "2.33.1"
crossbeam-channel = "0.5.13"
env_logger = "0.9.3"
home = "0.5"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
log = "0.4.22"
serde = "1.0.214"
serde_json = "1.0.132"
solana-account = "2.2.1"
solana-account-decoder = { path = "../../account-decoder" }
solana-bpf-loader-program = { path = "../../programs/bpf_loader" }
solana-client = { path = "../../client" }
solana-clock = "2.2.1"
solana-commitment-config = "2.2.1"
solana-compute-budget = { path = "../../compute-budget" }
solana-compute-budget-interface = "2.2.2"
solana-epoch-schedule = "2.2.1"
solana-hash = "2.2.1"
solana-instruction = "2.2.1"
solana-keypair = "2.2.1"
solana-logger = "=2.3.1"
solana-message = "2.3.0"
solana-nonce = "2.2.1"
solana-perf = { path = "../../perf" }
solana-program-pack = "2.2.1"
solana-program-runtime = { path = "../../program-runtime" }
solana-pubkey = "2.3.0"
solana-rent-collector = "2.2.1"
solana-rpc-client-api = { path = "../../rpc-client-api" }
solana-sdk-ids = "2.2.1"
solana-signature = "2.2.1"
solana-signer = "2.2.1"
solana-svm = { path = "../" }
solana-svm-callback = { path = "../../svm-callback" }
solana-svm-feature-set = { path = "../../svm-feature-set" }
solana-system-interface = "1.0"
solana-system-program = { path = "../../programs/system" }
solana-sysvar = "2.2.1"
solana-sysvar-id = "2.2.1"
solana-test-validator = { path = "../../test-validator" }
solana-transaction = "2.2.2"
solana-transaction-context = { path = "../../transaction-context" }
solana-transaction-error = "2.2.1"
solana-transaction-status = { path = "../../transaction-status" }
solana-validator-exit = "2.2.1"
solana-version = { path = "../../version" }
spl-associated-token-account = "7.0.0"
spl-token = "8.0.0"
spl-token-2022 = "8.0.0"
termcolor = "1.4.1"
thiserror = "1.0.68"
tokio = "1.29.1"
tokio-util = "0.7"
yaml-rust = "0.4"

[patch.crates-io]
crossbeam-epoch = { git = "https://github.com/anza-xyz/crossbeam", rev = "fd279d707025f0e60951e429bf778b4813d1b6bf" }
solana-curve25519 = { path = "../../curves/curve25519" }
solana-zk-sdk = { path = "../../zk-sdk" }
