[package]
name = "solana-vote"
description = "Solana vote"
documentation = "https://docs.rs/solana-vote"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "solana_vote"

[features]
agave-unstable-api = []
dev-context-only-utils = ["dep:rand", "dep:bincode"]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-vote-interface/frozen-abi",
]

[dependencies]
bincode = { workspace = true, optional = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { version = "0.9.2", optional = true }
serde = { workspace = true, features = ["rc"] }
solana-account = { workspace = true, features = ["bincode"] }
solana-bincode = { workspace = true }
solana-clock = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-packet = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-serialize-utils = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-svm-transaction = { workspace = true }
solana-transaction = { workspace = true, features = ["bincode"] }
solana-vote-interface = { workspace = true, features = ["bincode"] }
thiserror = { workspace = true }

[dev-dependencies]
agave-logger = { workspace = true }
arbitrary = { workspace = true }
bencher = { workspace = true }
bincode = { workspace = true }
rand = "0.9.2"
solana-keypair = { workspace = true }
solana-sha256-hasher = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true, features = ["bincode"] }
solana-vote = { path = ".", features = ["agave-unstable-api"] }
solana-vote-interface = { workspace = true, features = ["bincode", "dev-context-only-utils"] }
static_assertions = { workspace = true }

[[bench]]
name = "vote_account"
harness = false

[lints]
workspace = true
