[package]
name = "solana-stake-program"
description = "Solana Stake program helpers"
documentation = "https://docs.rs/solana-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "solana_stake_program"

[dependencies]
agave-feature-set = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
solana-account = { workspace = true }
solana-clock = { workspace = true }
solana-config-interface = { workspace = true, features = ["bincode"] }
solana-genesis-config = { workspace = true }
solana-native-token = { workspace = true }
solana-pubkey = { workspace = true }
solana-rent = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-stake-interface = { workspace = true, features = ["bincode"] }
solana-sysvar = { workspace = true }
solana-transaction-context = { workspace = true, features = ["bincode"] }
solana-vote-interface = { workspace = true, features = ["bincode"] }

[lints]
workspace = true
