[package]
name = "solana-stake-program"
description = "Solana Stake program"
documentation = "https://docs.rs/solana-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
agave-feature-set = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
solana-account = { workspace = true }
solana-bincode = { workspace = true }
solana-clock = { workspace = true }
solana-config-program-client = { workspace = true, features = ["serde"] }
solana-genesis-config = { workspace = true }
solana-instruction = { workspace = true }
solana-log-collector = { workspace = true }
solana-native-token = { workspace = true }
solana-packet = { workspace = true }
solana-program-runtime = { workspace = true }
solana-pubkey = { workspace = true, features = ["sha2"] }
solana-rent = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-stake-interface = { workspace = true }
solana-sysvar = { workspace = true }
solana-transaction-context = { workspace = true, features = ["bincode"] }
solana-type-overrides = { workspace = true }
solana-vote-interface = { workspace = true, features = ["bincode"] }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
solana-compute-budget = { workspace = true }
solana-epoch-rewards = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-svm-callback = { workspace = true }
solana-sysvar-id = { workspace = true }
solana-vote-program = { workspace = true, default-features = false }
test-case = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
name = "stake"
harness = false

[lints]
workspace = true
