[package]
name = "solana-rpc-client-api"
description = "Solana Client Common Utilities"
documentation = "https://docs.rs/solana-rpc-client-api"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
jsonrpc-core = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["rustls-tls"] }
reqwest-middleware = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
solana-account-decoder-client-types = { workspace = true }
solana-bundle = { workspace = true }
solana-clock = { workspace = true }
solana-rpc-client-types = { workspace = true }
solana-sdk = { workspace = true }
solana-signer = { workspace = true }
solana-svm = { workspace = true }
solana-transaction-error = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
thiserror = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
