[package]
name = "solana-tip-distributor"
version = "1.10.40"
edition = "2021"
license = "Apache-2.0"
description = "Collection of binaries used to distribute MEV rewards to delegators and validators."

[dependencies]
anchor-lang = { path = "../anchor/lang" }
bigdecimal = "0.3.0"
clap = { version = "3.2.5", features = ["derive", "env"] }
crossbeam-channel = "0.5"
env_logger = "0.9.0"
futures = "0.3.21"
im = "15.1.0"
itertools = "0.10.3"
log = "0.4.17"
num-traits = "0.2.15"
serde = "1.0.137"
serde_json = "1.0.81"
solana-client = { path = "../client", version = "=1.10.40" }
solana-genesis-utils = { path = "../genesis-utils", version = "=1.10.40" }
solana-ledger = { path = "../ledger", version = "=1.10.40" }
solana-merkle-tree = { path = "../merkle-tree", version = "=1.10.40" }
solana-program = { path = "../sdk/program", version = "=1.10.40" }
solana-runtime = { path = "../runtime", version = "=1.10.40" }
solana-sdk = { path = "../sdk", version = "=1.10.40" }
solana-stake-program = { path = "../programs/stake", version = "=1.10.40" }
thiserror = "1.0.31"
tip-distribution = { path = "../jito-programs/tip-payment/programs/tip-distribution", features = ["no-entrypoint"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "full"] }

[[bin]]
name = "stake-meta-generator"
path = "src/bin/stake-meta-generator.rs"

[[bin]]
name = "merkle-root-generator"
path = "src/bin/merkle-root-generator.rs"
