[package]
name = "agave-xdp-ebpf"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
include = ["Cargo.toml", "src/**", "README", "agave-xdp-prog"]

[[bin]]
name = "agave-xdp-prog"
path = "src/bin/agave-xdp-prog.rs"
required-features = ["ebpf"]

[features]
ebpf = []
agave-unstable-api = []

[target.'cfg(target_arch = "bpf")'.dependencies]
aya-ebpf = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }

[lints]
workspace = true
