[package]
name = "solana-compute-budget-program"
description = "Solana Compute Budget program"
documentation = "https://docs.rs/solana-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "solana_compute_budget_program"

[features]
svm-internal = []

[dependencies]
qualifier_attr = { workspace = true }
solana-program-runtime = { workspace = true }
