[package]
name = "agave-verified-packet-receiver"
description = "Agave Verified Packet Receiver Receiver"
documentation = "https://docs.rs/agave-verified-packet-receiver"
publish = true
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "agave_verified_packet_receiver"

[dependencies]
solana-perf = { workspace = true }
solana-streamer = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
solana-streamer = { workspace = true, features = ["dev-context-only-utils"] }
