[package]
name = "solana-svm-feature-set"
description = "Solana SVM Feature Set"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[dependencies]

[lints]
workspace = true
