[package]
name = "solana-svm-feature-set"
version = "3.0.9"
description = "Solana SVM Feature Set"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[dependencies]

[lints]
workspace = true
