[package]
name = "solana-udp-client"
description = "Solana UDP Client"
documentation = "https://docs.rs/solana-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
dev-context-only-utils = []

[dependencies]
async-trait = { workspace = true }
solana-connection-cache = { workspace = true }
solana-keypair = { workspace = true }
solana-net-utils = { workspace = true }
solana-streamer = { workspace = true }
solana-transaction-error = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
solana-net-utils = { workspace = true, features = ["dev-context-only-utils"] }
solana-packet = { workspace = true }
solana-streamer = { workspace = true, features = ["dev-context-only-utils"] }
