[package]
name = "solana-sbf-rust-poseidon"
description = "Solana SBF test program written in Rust"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
array-bytes = { workspace = true }
solana-msg = { workspace = true }
solana-poseidon = { workspace = true }
solana-program-entrypoint = { workspace = true }

[lints]
workspace = true
