[package]
name = "solana-loader-v2-interface"
description = "Solana non-upgradable BPF loader v2 instructions."
documentation = "https://docs.rs/solana-loader-v2-interface"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-instruction = { workspace = true, features = ["bincode", "std"], optional = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }

[features]
bincode = ["dep:solana-instruction", "serde"]
serde = ["dep:serde", "dep:serde_bytes", "dep:serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lints]
workspace = true
