[package]
name = "agave-votor-messages"
documentation = "https://docs.rs/agave-votor-messages"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
agave-unstable-api = []
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-hash/frozen-abi",
    "solana-bls-signatures/frozen-abi",
]

[dependencies]
agave-logger = { workspace = true }
serde = { workspace = true }
solana-bls-signatures = { workspace = true, features = [
    "bytemuck", "solana-signer-derive",
] }
solana-clock = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-hash = { workspace = true, features = ["serde"] }

[lints]
workspace = true
