[package]
name = "solana-genesis"
documentation = "https://docs.rs/solana-genesis"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_genesis"

[[bin]]
name = "solana-genesis"
path = "src/main.rs"

[features]
default = ["agave-unstable-api"]
agave-unstable-api = []

[dependencies]
agave-feature-set = { workspace = true }
agave-logger = { workspace = true }
agave-snapshots = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
solana-account = "=3.2.0"
solana-bls-signatures = { workspace = true }
solana-clap-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-clock = "=3.0.0"
solana-cluster-type = "=3.0.0"
solana-commitment-config = "=3.0.0"
solana-entry = { workspace = true }
solana-epoch-schedule = "=3.0.0"
solana-feature-gate-interface = "=3.0.0"
solana-fee-calculator = "=3.0.0"
solana-genesis-config = "=3.0.0"
solana-genesis-utils = { workspace = true }
solana-inflation = "=3.0.0"
solana-keypair = "=3.0.1"
solana-ledger = { workspace = true }
solana-loader-v3-interface = "6.1.0"
solana-native-token = "=3.0.0"
solana-poh-config = "=3.0.0"
solana-pubkey = { version = "=3.0.0", default-features = false }
solana-rent = "=3.0.0"
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-runtime = { workspace = true }
solana-sdk-ids = "=3.0.0"
solana-signer = "=3.0.0"
solana-stake-interface = { version = "=2.0.1", features = ["borsh"] }
solana-time-utils = "3.0.0"
solana-version = { workspace = true }
solana-vote-program = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
solana-borsh = { workspace = true }
solana-genesis = { path = ".", features = ["agave-unstable-api"] }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solana-vote = { workspace = true }
test-case = { workspace = true }
