[package]
name = "solana-genesis"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-genesis"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
agave-feature-set = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
solana-account = "=2.2.1"
solana-accounts-db = { workspace = true }
solana-clap-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-clock = "=2.2.1"
solana-commitment-config = "=2.2.1"
solana-entry = { workspace = true }
solana-epoch-schedule = "=2.2.1"
solana-feature-gate-interface = "=2.2.1"
solana-fee-calculator = "=2.2.1"
solana-genesis-config = "=2.2.1"
solana-inflation = "=2.2.1"
solana-keypair = "=2.2.1"
solana-ledger = { workspace = true }
solana-loader-v3-interface = "=3.0.0"
solana-logger = "=2.3.1"
solana-native-token = "=2.2.1"
solana-poh-config = "=2.2.1"
solana-pubkey = { version = "=2.2.1", default-features = false }
solana-rent = "=2.2.1"
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-runtime = { workspace = true }
solana-sdk-ids = "=2.2.1"
solana-signer = "=2.2.1"
solana-stake-interface = "=1.2.1"
solana-stake-program = { workspace = true }
solana-time-utils = "2.2.1"
solana-version = { workspace = true }
solana-vote-program = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
solana-borsh = { workspace = true }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[[bin]]
name = "solana-genesis"
path = "src/main.rs"

[lib]
name = "solana_genesis"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
