[package]
name = "agave-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/agave-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
solana-clap-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-cli-output = { workspace = true }
solana-hash = "=2.2.1"
solana-logger = "=2.3.1"
solana-metrics = { workspace = true }
solana-native-token = "=2.2.1"
solana-notifier = { workspace = true }
solana-pubkey = { version = "=2.2.1", default-features = false }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
