[package]
name = "agave-watchtower"
documentation = "https://docs.rs/agave-watchtower"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
agave-unstable-api = []

[dependencies]
agave-logger = { workspace = true }
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
solana-clap-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-cli-output = { workspace = true }
solana-hash = "=3.1.0"
solana-metrics = { workspace = true }
solana-native-token = "=3.0.0"
solana-notifier = { workspace = true }
solana-pubkey = { version = "=3.0.0", default-features = false }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-version = { workspace = true }
