[package]
name = "solana-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true }
serde_derive = { workspace = true }
solana-account-decoder = { workspace = true }
solana-clap-utils = { workspace = true }
solana-cli-config = { workspace = true }
solana-clock = { workspace = true }
solana-commitment-config = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-message = { workspace = true }
solana-native-token = { workspace = true }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-remote-wallet = { workspace = true, features = ["default"] }
solana-rpc-client = { workspace = true, features = ["default"] }
solana-rpc-client-api = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-stake-interface = { workspace = true }
solana-system-interface = { workspace = true }
solana-transaction = { workspace = true }
solana-transaction-status = { workspace = true }
solana-version = { workspace = true }
spl-associated-token-account = { version = "=7.0.0", features = ["no-entrypoint"] }
spl-token = { version = "=8.0.0", features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
solana-logger = { workspace = true }
solana-streamer = { workspace = true }
solana-test-validator = { workspace = true }
solana-transaction-error = { workspace = true }
