[package]
name = "xtask"
version = "0.1.0"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
description = "Blockchain, Rebuilt for Scale"
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"
publish = false

# Prevents auto-detection of parent workspace (ie. git worktrees).
[workspace]

[features]
agave-unstable-api = []
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.31", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.28"
semver = "1.0.27"
tokio = { version = "1.48.0", features = ["full"] }
toml_edit = { version = "0.23.7", features = ["serde"] }
walkdir = "2.5.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
serial_test = "3.2.0"
tempfile = "3.23.0"
