[package]
name = "solana-wen-restart"
description = "Automatic repair and restart protocol"
documentation = "https://github.com/solana-foundation/solana-improvement-documents/pull/46"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_wen_restart"

[features]
agave-unstable-api = []

[dependencies]
agave-snapshots = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
rayon = { workspace = true }
solana-clock = { workspace = true }
solana-entry = { workspace = true }
solana-genesis-utils = { workspace = true }
solana-gossip = { workspace = true }
solana-hash = { workspace = true }
solana-ledger = { workspace = true }
solana-net-utils = { workspace = true }
solana-pubkey = { workspace = true }
solana-runtime = { workspace = true }
solana-shred-version = { workspace = true }
solana-svm-timings = { workspace = true }
solana-time-utils = { workspace = true }
solana-vote = { workspace = true }
solana-vote-interface = { workspace = true }
solana-vote-program = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }

# windows users should install the protobuf compiler manually and set the PROTOC
# envar to point to the installed binary
[target."cfg(not(windows))".build-dependencies]
protobuf-src = { workspace = true }

[dev-dependencies]
agave-logger = { workspace = true }
agave-snapshots = { workspace = true }
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
rand = "0.8.5"
serial_test = { workspace = true }
solana-entry = { workspace = true }
solana-keypair = { workspace = true }
solana-ledger = { workspace = true, features = ["dev-context-only-utils"] }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solana-signer = { workspace = true }
tempfile = { workspace = true }
