[package]
name = "solana-svm-callback"
version = "3.0.9"
description = "Solana SVM callback"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = false

[dependencies]
solana-account = { workspace = true }
solana-clock = { workspace = true }
solana-precompile-error = { workspace = true }
solana-pubkey = { workspace = true }

[lints]
workspace = true
