[package]
name = "agave-scheduling-utils"
description = "Common utilities for building Agave scheduler implementations"
documentation = "https://docs.rs/agave-scheduling-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
agave-unstable-api = []

[dependencies]
agave-scheduler-bindings = { workspace = true }
ahash = { workspace = true }
solana-pubkey = { workspace = true }
solana-transaction-error = { workspace = true }

[target."cfg(unix)".dependencies]
agave-transaction-view = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["socket", "uio"] }
rts-alloc = { workspace = true }
shaq = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target."cfg(unix)".dev-dependencies]
agave-scheduler-bindings = { workspace = true, features = ["dev-context-only-utils"] }

[lints]
workspace = true
