[package]
name = "agave-votor"
documentation = "https://docs.rs/agave-votor"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
agave-unstable-api = []
dev-context-only-utils = ["solana-runtime/dev-context-only-utils"]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-accounts-db/frozen-abi",
    "solana-bloom/frozen-abi",
    "solana-ledger/frozen-abi",
    "solana-runtime/frozen-abi",
    "solana-signature/frozen-abi",
    "agave-votor-messages/frozen-abi",
]

[dependencies]
agave-logger = { workspace = true }
agave-votor-messages = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
bitvec = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true, features = ["rayon", "raw-api"] }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
parking_lot = { workspace = true }
qualifier_attr = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
solana-account = { workspace = true }
solana-accounts-db = { workspace = true }
solana-bloom = { workspace = true }
solana-bls-signatures = { workspace = true }
solana-client = { workspace = true }
solana-clock = { workspace = true }
solana-connection-cache = { workspace = true }
solana-entry = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
solana-genesis-config = { workspace = true }
solana-gossip = { workspace = true }
solana-hash = { workspace = true }
solana-keypair = { workspace = true }
solana-ledger = { workspace = true }
solana-measure = { workspace = true }
solana-metrics = { workspace = true }
solana-pubkey = { workspace = true }
solana-rpc = { workspace = true }
solana-runtime = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-signer-store = { workspace = true }
solana-time-utils = { workspace = true }
solana-transaction = { workspace = true }
solana-transaction-error = { workspace = true }
solana-vote = { workspace = true }
solana-vote-program = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
solana-net-utils = { workspace = true }
solana-perf = { workspace = true, features = ["dev-context-only-utils"] }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solana-sdk-ids = { workspace = true }
solana-streamer = { workspace = true, features = ["dev-context-only-utils"] }
tempfile = { workspace = true }
test-case = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true
