[package]
name = "solana-svm-transaction"
description = "Solana SVM Transaction"
documentation = "https://docs.rs/solana-svm-transaction"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-hash = { workspace = true }
solana-message = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-signature = { workspace = true }
solana-transaction = { workspace = true }

[dev-dependencies]
solana-message = { workspace = true, features = ["bincode"] }
solana-nonce = { workspace = true }
solana-system-interface = { workspace = true }
static_assertions = { workspace = true }
test-case = { workspace = true }
