# This package only exists to avoid circular dependencies during cargo publish:
# solana-runtime -> solana-address-program -> solana-program-test -> solana-runtime

[package]
name = "solana-address-lookup-table-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
agave-feature-set = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
criterion = { workspace = true }
solana-account = { workspace = true }
solana-address-lookup-table-program = { workspace = true }
solana-instruction = { workspace = true }
solana-program-runtime = { workspace = true }
solana-program-test = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-system-program = { workspace = true }

[[bench]]
name = "address_lookup_table"
harness = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
