[package]
name = "json-rpc-client"
description = "Reference example using Solana SVM API for RPC API"
version = { workspace = true }
edition = { workspace = true }
publish = false

[features]
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
borsh = { workspace = true }
clap = { workspace = true }
home = { workspace = true }
solana-client = { workspace = true }
solana-commitment-config = { workspace = true }
solana-instruction = { workspace = true }
solana-keypair = { workspace = true }
solana-message = { workspace = true }
solana-pubkey = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true }
thiserror = { workspace = true }
yaml-rust = { workspace = true }
