[store]
dir = "target/nextest"

[test-groups]
build-sbf = { max-threads = 1 }

[profile.ci]
failure-output = "immediate-final"
slow-timeout = { period = "60s", terminate-after = 1 }
retries = { backoff = "fixed", count = 3, delay = "1s" }

[profile.ci.junit]
path = "junit.xml"

[[profile.ci.overrides]]
filter = "package(solana-zk-elgamal-proof-program-tests) & test(/^test_batched_range_proof_u256$/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-turbine) | package(solana-gossip) | package(solana-perf)"
retries = 0

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^test_star_network_push_star_200/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^test_star_network_push_ring_200/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^gossip_ring/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-gossip) & test(/^cluster_info::tests::new_with_external_ip_test_random/)"
threads-required = "num-cpus"

[[profile.ci.overrides]]
filter = "package(solana-cargo-build-sbf)"
test-group = "build-sbf"

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_kill_partition_switch_threshold_progress$/)'
slow-timeout = { period = "60s", terminate-after = 10 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_kill_partition_switch_threshold_no_progress$/)'
slow-timeout = { period = "60s", terminate-after = 10 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_run_test_load_program_accounts_partition_root$/)'
slow-timeout = { period = "60s", terminate-after = 10 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_fork_choice_refresh_old_votes$/)'
slow-timeout = { period = "60s", terminate-after = 5 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_cluster_partition_1_1_1$/)'
slow-timeout = { period = "60s", terminate-after = 4 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_wait_for_max_stake$/)'
slow-timeout = { period = "60s", terminate-after = 4 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_snapshots_restart_validity$/)'
slow-timeout = { period = "60s", terminate-after = 4 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_slot_hash_expiry$/)'
slow-timeout = { period = "60s", terminate-after = 4 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_kill_heaviest_partition$/)'
slow-timeout = { period = "60s", terminate-after = 4 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster) & test(/^test_boot_from_local_state$/)'
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.ci.overrides]]
filter = 'package(solana-local-cluster)'
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'package(solana-cargo-build-sbf)'
slow-timeout = { period = "60s", terminate-after = 5 }

[[profile.ci.overrides]]
filter = 'package(solana-ledger) & test(/^shred::merkle::test::test_merkle_tree_round_trip/)'
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.ci.overrides]]
filter = 'package(solana-core) & test(/^banking_stage::consumer::tests::test_bank_nonce_update_blockhash_queried_before_transaction_record/)'
slow-timeout = { period = "60s", terminate-after = 8 }

[[profile.ci.overrides]]
filter = 'package(solana-core) & test(/^banking_stage::consumer::tests::test_bank_process_and_record_transactions/)'
slow-timeout = { period = "60s", terminate-after = 8 }

[[profile.ci.overrides]]
filter = 'package(solana-core) & test(/^test_slots_to_snapshot/)'
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'package(solana-core) & test(/^test_snapshots_have_expected_epoch_accounts_hash/)'
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'package(solana-client-test) & test(/^test_send_and_confirm_transactions_in_parallel_with_tpu_client/)'
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.ci.overrides]]
filter = 'package(solana-runtime) & test(/^bank_forks::tests::test_bank_forks_new_rw_arc_memory_leak/)'
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.ci.overrides]]
filter = 'package(solana-runtime) & test(/^bank::tests::test_race_register_tick_freeze/)'
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.ci.overrides]]
filter = 'package(solana-svm) & test(/^execute_fixtures/)'
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = "package(solana-accounts-cluster-bench)"
threads-required = "num-cpus"
