[package]
name = "solana-zk-elgamal-proof-program"
description = "Solana Zk ElGamal Proof Program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
solana-instruction = { workspace = true, features = ["std"] }
solana-log-collector = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-zk-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
curve25519-dalek = { workspace = true }

[[bench]]
name = "verify_proofs"
harness = false
