[package]
name = "solana-rpc-client-nonce-utils"
description = "Solana RPC Client Nonce Utilities"
documentation = "https://docs.rs/solana-nonce-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "2.33.0", optional = true }
solana-account = { workspace = true }
solana-clap-utils = { workspace = true, optional = true }
solana-commitment-config = { workspace = true }
solana-hash = { workspace = true }
solana-message = { workspace = true }
solana-nonce = { workspace = true }
solana-pubkey = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk-ids = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
solana-account-decoder = { workspace = true }
solana-fee-calculator = { workspace = true }
solana-keypair = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sha256-hasher = { workspace = true }
solana-signer = { workspace = true }
solana-system-interface = { workspace = true }
solana-transaction = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
default = []
clap = ["dep:clap", "dep:solana-clap-utils"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
