[package]
name = "jito-priority-fee-sharing"
description = "Priority fee sharing through the Jito protocol"

version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "priority_fee_sharing"
crate-type = ["lib"]

[[bin]]
name = "priority-fee-sharing"
path = "src/bin/main.rs"

[dependencies]
# Workspace dependencies
anyhow = { workspace = true }
bincode = { workspace = true }

# External dependencies
clap = { version = "4.5.31", features = ["derive", "env"] }
csv = "1.3.1"
dotenv = "0.15"
env_logger = "0.10.0"
log = { workspace = true }
prometheus = { version = "0.13", features = ["push"] }
rocksdb = "0.23.0"
serde = { workspace = true }
solana-account = { workspace = true, features = ["bincode"] }
solana-client = { workspace = true }
solana-commitment-config = { workspace = true }
solana-compute-budget-interface = { workspace = true }
solana-metrics = { workspace = true }
solana-pubkey = { workspace = true }
solana-reward-info = { workspace = true }
solana-rpc-client = { workspace = true }
solana-sdk = { workspace = true }
solana-system-interface = { workspace = true }
solana-vote-interface = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
