[package]
name = "jito-priority-fee-sharing"
description = "Priority fee sharing through the Jito protocol"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
clap = { version = "4.5.31", features = ["derive", "env"] }
enum-iterator = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
solana-account = { workspace = true, features = ["bincode"] }
solana-clock = { workspace = true }
solana-compute-budget = { workspace = true }
solana-epoch-rewards = { workspace = true }
solana-hash = { workspace = true }
solana-metrics = { workspace = true, optional = true }
solana-pubkey = { workspace = true }
solana-sdk = { workspace = true }
solana-rpc-client = { workspace = true }
solana-client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
csv = "1.3.1"
rocksdb = "=0.22.0"
spl-memo = "6.0.0"
env_logger = "0.10.0"

[dev-dependencies]
uuid = { version = "1.3", features = ["v4"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "priority_fee_sharing"

[lints]
workspace = true
