[package]
name = "solana-shred-version"
description = "Calculation of shred versions."
documentation = "https://docs.rs/solana-shred-version"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-hard-forks = { workspace = true }
solana-hash = { workspace = true }
solana-sha256-hasher = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
