[package]
name = "solana-cargo-build-sbf"
description = "Compile a local package and all of its dependencies using the Solana SBF SDK"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "cargo-build-sbf"
path = "src/main.rs"

[features]
program = []

[dependencies]
bzip2 = { workspace = true }
cargo_metadata = { workspace = true }
clap = { version = "3.1.5", features = ["cargo", "env"] }
itertools = { workspace = true }
log = { workspace = true, features = ["std"] }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "rustls-tls", "rustls-tls-native-roots", "json" ] }
semver = { workspace = true }
serde = { workspace = true }
solana-file-download = "=3.1.0"
solana-keypair = "=3.0.0"
solana-logger = "=3.0.0"
tar = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
serial_test = { workspace = true }
